package types

import "encoding/json"

// SubAgentProposal is proposed by an Agent (via LLM) to decompose the current task
// into parallel sub-tasks. Validated by SubAgentValidator before execution.
type SubAgentProposal struct {
	// Why the agent wants to decompose (for validation and tracing)
	Reason string `json:"reason"`

	// Expected outcome after all sub-tasks complete (for reducer)
	Goal string `json:"goal"`

	// Sub-tasks to execute in parallel
	SubTasks []SubTask `json:"sub_tasks"`

	// Hint for how the reducer should merge results
	ReduceHint string `json:"reduce_hint,omitempty"`
}

// SubTask describes a single sub-task within a SubAgentProposal.
// Proposed by LLM, validated by SubAgentValidator, then converted to SubAgentRequest.
type SubTask struct {
	// Unique ID within the proposal (e.g. "st-1"), assigned by LLM
	ID string `json:"id"`

	// Short human-readable description
	Title string `json:"title"`

	// Name of the SubAgent to execute this task (looked up in SubAgentRegistry)
	SubAgent string `json:"sub_agent"`

	// What this sub-task should accomplish (injected into AgentContext.Objective)
	Objective string `json:"objective"`

	// File/directory scope to constrain the sub-agent's work
	Scope []string `json:"scope"`

	// Additional constraints for the sub-agent
	Constraints []string `json:"constraints,omitempty"`

	// Optional input data passed to the sub-agent
	InputData json.RawMessage `json:"input_data,omitempty"`
}

// SubAgentRequest is the validated, immutable execution request for a SubAgent.
// Generated by SubAgentValidator from a SubTask.
type SubAgentRequest struct {
	// Runtime-assigned unique ID (traceID + subTask.ID)
	ID string `json:"id"`

	// SubAgent name (from SubAgentRegistry)
	SubAgent string `json:"sub_agent"`

	// Sub-task objective
	Objective string `json:"objective"`

	// Scope constraint
	Scope []string `json:"scope"`

	// Additional constraints
	Constraints []string `json:"constraints,omitempty"`

	// Optional input data
	InputData json.RawMessage `json:"input_data,omitempty"`

	// Shared read-only view of BusContext. All parallel SubAgents share the same pointer.
	// SubAgents read through BuildSubAgentContext(); never write to this directly.
	ReadView *BusContext `json:"-"`
}

// SubAgentResult is the isolated write buffer for a single SubAgent execution.
// Each SubAgent writes only to its own result; the SubAgentReducer merges all results.
type SubAgentResult struct {
	// Matches SubAgentRequest.ID
	RequestID string `json:"request_id"`

	// SubAgent name that produced this result
	SubAgent string `json:"sub_agent"`

	// Raw output data
	Output json.RawMessage `json:"output,omitempty"`

	// Discovered facts
	Facts []RepoFact `json:"facts,omitempty"`

	// Structured evidence emitted by the sub-agent.
	EvidenceItems []EvidenceItem `json:"evidence_items,omitempty"`

	// Compact dataflow findings emitted by the sub-agent.
	FlowFindings []FlowFindingDigest `json:"flow_findings,omitempty"`

	// Tool invocation results
	Tools []ToolResult `json:"tool_results,omitempty"`

	// MCP responses
	MCPResps []MCPResponse `json:"mcp_responses,omitempty"`

	// Signal updates (merged with OR semantics by reducer)
	Signals *ExecutionSignals `json:"signals,omitempty"`

	// Error if execution failed
	Error string `json:"error,omitempty"`
}
