package orchestrator

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/hanchaoqun/codrax/internal/types"
)

type excludedAnswerCategory string

const (
	excludedAnswerCategoryVariable  excludedAnswerCategory = "variable"
	excludedAnswerCategoryTest      excludedAnswerCategory = "test"
	excludedAnswerCategoryGenerated excludedAnswerCategory = "generated"
	excludedAnswerCategoryPrivate   excludedAnswerCategory = "private"
)

type excludedAnswerCategorySpec struct {
	category         excludedAnswerCategory
	objectiveMarkers []string
	answerMarkers    []string
}

var (
	codeIdentifierTokenRE = regexp.MustCompile(`[@$]?[A-Za-z_][A-Za-z0-9_]*[!?]?`)
	inlineCodeTokenRE     = regexp.MustCompile("`([^`]+)`")
	excludedCategorySpecs = []excludedAnswerCategorySpec{
		{
			category: excludedAnswerCategoryVariable,
			objectiveMarkers: []string{
				"变量", "variable", "variables", "vars", " var ",
			},
			answerMarkers: []string{
				"变量", "variables", "variable", "vars",
			},
		},
		{
			category: excludedAnswerCategoryTest,
			objectiveMarkers: []string{
				"测试", "test", "tests", "spec", "specs",
			},
			answerMarkers: []string{
				"测试", "test files", "tests", "test", "specs", "spec",
			},
		},
		{
			category: excludedAnswerCategoryGenerated,
			objectiveMarkers: []string{
				"生成文件", "生成代码", "generated files", "generated code", "generated", "auto-generated", "autogenerated",
			},
			answerMarkers: []string{
				"生成文件", "生成代码", "generated files", "generated code", "generated", "auto-generated", "autogenerated",
			},
		},
		{
			category: excludedAnswerCategoryPrivate,
			objectiveMarkers: []string{
				"私有", "非公开", "private", "unexported",
			},
			answerMarkers: []string{
				"私有", "非公开", "private helpers", "private helper", "unexported helpers", "unexported helper", "private", "unexported", "helpers", "helper",
			},
		},
	}
)

// runUserExcludedCategoryAnswerCheck prevents negative evidence from leaking
// back into the user-visible principal answer. Exploration may collect
// excluded candidates to prove scope, but if the user explicitly says "do not
// list variables", the final answer should say the category is excluded, not
// print the candidate names/paths as a side list. The check is category-spec
// driven so the same boundary covers variables, tests, generated files, and
// private helpers without prompt-only repair.
func runUserExcludedCategoryAnswerCheck(doc *types.AnswerDocumentV2, mut *types.MutableState) []types.Violation {
	if doc == nil || mut == nil || len(doc.Blocks) == 0 {
		return nil
	}
	categories := excludedCategoriesFromObjective(mut.Objective())
	if len(categories) == 0 {
		return nil
	}

	var out []types.Violation
	for _, block := range doc.Blocks {
		prose := proseTextOfBlock(block)
		if strings.TrimSpace(prose) == "" {
			continue
		}
		for _, category := range categories {
			tokens := leakedExcludedCategoryTokens(prose, category)
			if len(tokens) == 0 {
				continue
			}
			out = append(out, types.Violation{
				Kind:       types.ViolMustExclude,
				Detail:     fmt.Sprintf("answer block %q names user-excluded %s candidate(s): %s", block.ID, category, strings.Join(tokens, ", ")),
				Repair:     fmt.Sprintf("Remove the concrete %s candidate name(s) %s from the user-visible answer. It is OK to say the %s category was excluded; do not list excluded candidate identifiers unless the user explicitly asks for excluded candidates.", category, strings.Join(tokens, ", "), category),
				Stage:      string(types.StageFinalize),
				ClusterKey: "user_excluded_category:" + string(category) + ":" + block.ID,
				SuspectedRoot: types.SuspectedRoot{
					IRField:    "answer_document.blocks." + block.ID + ".prose",
					Reason:     "final answer copied concrete candidates from a user-excluded category",
					Confidence: 0.8,
				},
			})
		}
	}
	return out
}

func excludedCategoriesFromObjective(objective string) []excludedAnswerCategory {
	lower := strings.ToLower(strings.TrimSpace(objective))
	if lower == "" || !containsObjectiveExclusionMarker(lower) {
		return nil
	}
	var out []excludedAnswerCategory
	for _, spec := range excludedCategorySpecs {
		if containsAnyCategoryMarker(objective, lower, spec.objectiveMarkers) {
			out = append(out, spec.category)
		}
	}
	return out
}

func containsObjectiveExclusionMarker(lower string) bool {
	for _, marker := range []string{
		"不要列", "不列", "不要包括", "不要包含", "不包括", "不包含", "排除", "除外",
		"do not list", "don't list", "dont list", "do not include", "don't include", "dont include",
		"exclude", "excluding", "without", "omit",
	} {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return false
}

func leakedExcludedCategoryTokens(prose string, category excludedAnswerCategory) []string {
	seen := map[string]bool{}
	for _, sentence := range splitExcludedCategoryProse(prose) {
		if !sentenceMentionsExcludedCategory(sentence, category) {
			continue
		}
		if !sentenceFramesExcludedCategoryList(sentence, category) {
			continue
		}
		for _, token := range codeTokensInExcludedCategorySentence(sentence, category) {
			if token == "" || seen[token] {
				continue
			}
			seen[token] = true
		}
	}
	out := make([]string, 0, len(seen))
	for token := range seen {
		out = append(out, token)
	}
	sort.Strings(out)
	if len(out) > 8 {
		return out[:8]
	}
	return out
}

func splitExcludedCategoryProse(prose string) []string {
	fields := strings.FieldsFunc(prose, func(r rune) bool {
		switch r {
		case '\n', '\r', '。', '；', ';':
			return true
		default:
			return false
		}
	})
	out := make([]string, 0, len(fields))
	for _, field := range fields {
		if s := strings.TrimSpace(field); s != "" {
			out = append(out, s)
		}
	}
	return out
}

func sentenceMentionsExcludedCategory(sentence string, category excludedAnswerCategory) bool {
	lower := strings.ToLower(sentence)
	if spec, ok := excludedCategorySpecFor(category); ok {
		return containsAnyCategoryMarker(sentence, lower, spec.answerMarkers)
	}
	return false
}

func sentenceFramesExcludedCategoryList(sentence string, category excludedAnswerCategory) bool {
	lower := strings.ToLower(sentence)
	if containsObjectiveExclusionMarker(lower) ||
		strings.Contains(lower, "excluded") ||
		strings.Contains(lower, "not listed") ||
		strings.Contains(lower, "not included") {
		return true
	}
	if spec, ok := excludedCategorySpecFor(category); ok {
		for _, marker := range spec.answerMarkers {
			for _, suffix := range []string{"（", "(", ":", "："} {
				if containsCategoryMarkerWithSuffix(sentence, lower, marker, suffix) {
					return true
				}
			}
		}
	}
	return false
}

func codeTokensInExcludedCategorySentence(sentence string, category excludedAnswerCategory) []string {
	seen := map[string]bool{}
	add := func(raw string, inlineCode bool, allowPlainLower bool) {
		token := strings.TrimSpace(raw)
		token = strings.Trim(token, "`'\"“”‘’[](){}<>:,，、")
		if !looksLikeExcludedCategoryCodeToken(token, inlineCode, allowPlainLower) {
			return
		}
		seen[token] = true
	}
	scan := func(text string, allowPlainLower bool) {
		for _, match := range inlineCodeTokenRE.FindAllStringSubmatch(text, -1) {
			if len(match) > 1 {
				add(match[1], true, true)
			}
		}
		textWithoutInlineCode := inlineCodeTokenRE.ReplaceAllString(text, " ")
		for _, token := range codeIdentifierTokenRE.FindAllString(textWithoutInlineCode, -1) {
			add(token, false, allowPlainLower)
		}
	}
	scanInlineOnly := func(text string) {
		for _, match := range inlineCodeTokenRE.FindAllStringSubmatch(text, -1) {
			if len(match) > 1 {
				add(match[1], true, true)
			}
		}
	}
	segments := excludedCategoryCandidateSegments(sentence, category)
	if len(segments) > 0 {
		for _, segment := range segments {
			scan(segment, true)
		}
	} else {
		scanInlineOnly(sentence)
	}
	out := make([]string, 0, len(seen))
	for token := range seen {
		out = append(out, token)
	}
	sort.Strings(out)
	return out
}

func excludedCategoryCandidateSegments(sentence string, category excludedAnswerCategory) []string {
	spec, ok := excludedCategorySpecFor(category)
	if !ok {
		return nil
	}
	lower := strings.ToLower(sentence)
	seen := map[string]bool{}
	var out []string
	for _, marker := range spec.answerMarkers {
		if marker == "" {
			continue
		}
		haystack := lower
		needle := strings.ToLower(marker)
		if containsNonASCII(marker) {
			haystack = sentence
			needle = marker
		}
		for offset := 0; offset < len(haystack); {
			idx := strings.Index(haystack[offset:], needle)
			if idx < 0 {
				break
			}
			start := offset + idx + len(needle)
			if start > len(sentence) {
				break
			}
			if segment, ok := excludedCategorySegmentAfterMarker(sentence[start:]); ok {
				segment = strings.TrimSpace(segment)
				if segment != "" && !seen[segment] {
					seen[segment] = true
					out = append(out, segment)
				}
			}
			offset = start
		}
	}
	return out
}

func excludedCategorySegmentAfterMarker(after string) (string, bool) {
	after = strings.TrimLeftFunc(after, unicode.IsSpace)
	for _, pair := range [][2]string{{"（", "）"}, {"(", ")"}} {
		if strings.HasPrefix(after, pair[0]) {
			body := after[len(pair[0]):]
			end := strings.Index(body, pair[1])
			if end < 0 {
				return "", false
			}
			return body[:end], true
		}
	}
	for _, sep := range []string{"：", ":"} {
		if strings.HasPrefix(after, sep) {
			return after[len(sep):], true
		}
	}
	return "", false
}

func looksLikeExcludedCategoryCodeToken(token string, inlineCode bool, allowPlainLower bool) bool {
	if len([]rune(token)) < 3 {
		return false
	}
	lower := strings.ToLower(token)
	switch lower {
	case "variable", "variables", "vars", "public", "private", "internal", "excluded", "exclude", "excluding",
		"include", "included", "listed", "candidate", "candidates", "category", "categories",
		"function", "functions", "type", "types", "const", "block", "file", "files", "test", "tests",
		"spec", "specs", "generated", "autogenerated", "helper", "helpers", "none", "nothing", "omitted",
		"ignored", "requested", "required", "according", "answer", "summary", "scope", "only", "also":
		return false
	}
	if inlineCode {
		return true
	}
	if allowPlainLower && isIdentifierLikeToken(token) {
		return true
	}
	return hasIdentifierCodeShape(token)
}

func hasIdentifierCodeShape(token string) bool {
	token = strings.TrimLeft(token, "@$")
	if strings.Contains(token, "_") {
		return true
	}
	var prev rune
	hasLower := false
	hasUpper := false
	for _, r := range token {
		if unicode.IsLower(r) {
			hasLower = true
		}
		if unicode.IsUpper(r) {
			hasUpper = true
			if prev != 0 && unicode.IsLower(prev) {
				return true
			}
		}
		prev = r
	}
	return hasLower && hasUpper
}

func excludedCategorySpecFor(category excludedAnswerCategory) (excludedAnswerCategorySpec, bool) {
	for _, spec := range excludedCategorySpecs {
		if spec.category == category {
			return spec, true
		}
	}
	return excludedAnswerCategorySpec{}, false
}

func containsAnyCategoryMarker(original string, lower string, markers []string) bool {
	for _, marker := range markers {
		if marker == "" {
			continue
		}
		if containsCategoryMarker(original, lower, marker) {
			return true
		}
	}
	return false
}

func containsCategoryMarker(original string, lower string, marker string) bool {
	if containsNonASCII(marker) {
		return strings.Contains(original, marker)
	}
	return containsASCIIWordishMarker(lower, strings.ToLower(marker))
}

func containsCategoryMarkerWithSuffix(original string, lower string, marker string, suffix string) bool {
	if containsNonASCII(marker) {
		return strings.Contains(original, marker+suffix)
	}
	needle := strings.ToLower(marker) + suffix
	return containsASCIIWordishMarker(lower, needle)
}

func containsNonASCII(s string) bool {
	for _, r := range s {
		if r > unicode.MaxASCII {
			return true
		}
	}
	return false
}

func isIdentifierLikeToken(token string) bool {
	token = strings.TrimLeft(token, "@$")
	token = strings.TrimRight(token, "!?")
	if token == "" {
		return false
	}
	for i, r := range token {
		switch {
		case r == '_':
			continue
		case i > 0 && unicode.IsDigit(r):
			continue
		case unicode.IsLetter(r):
			continue
		default:
			return false
		}
	}
	return true
}

func containsASCIIWordishMarker(haystack string, marker string) bool {
	if marker == "" {
		return false
	}
	for offset := 0; offset < len(haystack); {
		idx := strings.Index(haystack[offset:], marker)
		if idx < 0 {
			return false
		}
		start := offset + idx
		end := start + len(marker)
		if asciiMarkerBoundaryOK(haystack, start, end) {
			return true
		}
		offset = start + 1
	}
	return false
}

func asciiMarkerBoundaryOK(s string, start int, end int) bool {
	if start > 0 && isASCIIIdentByte(s[start-1]) {
		return false
	}
	if end < len(s) && isASCIIIdentByte(s[end]) {
		return false
	}
	return true
}

func isASCIIIdentByte(b byte) bool {
	return (b >= 'a' && b <= 'z') ||
		(b >= 'A' && b <= 'Z') ||
		(b >= '0' && b <= '9') ||
		b == '_'
}
