package skill

// TraceJankQueryContract is shared by trace exploration and the tool schema.
// It is guidance for typed queries, not a classifier over request prose.
const TraceJankQueryContract = "JANK MARKERS: jank_event_sync markers report start_ts/end_ts in native nanoseconds, jank_frames (2 means a stall of two frames), and appid. For numeric questions use event_search with event_field_filters, for example [{\"field\":\"jank_frames\",\"op\":\"gte\",\"value\":\"2\"}]; add {\"field\":\"appid\",\"op\":\"eq\",\"value\":\"27599\"} for one app. Conditions are ANDed; eq/ne/gt/gte/lt/lte support equality, thresholds and ranges. These match validated numeric fields, not text patterns or regex. Use quoted decimal integers to preserve nanosecond precision. appid is the marker's application identifier, not the emitter TID. Explicit pid filters the emitter TID; thread keeps its existing name/text matching and is not identity proof. Numeric field queries do not inherit an implicit target-thread filter. time_start/time_end filter the reporting event's header timestamp in query-axis seconds; start_ts/end_ts field conditions filter the reported symptom endpoints in source-axis nanoseconds. Do not substitute one selection for the other. " + TraceJankClockContract + " Preserve the native fields, reporting timestamp and physical source line in the answer. Compute the reported duration as (end_ts - start_ts) / 1,000,000 milliseconds using the exact integers before conversion. For all/count questions distinguish matched_total from emitted rows and inspect coverage/truncation before claiming completeness; continue with the same filters when paging. Explain these as total matches, shown records and search scope in user-facing language. A marker locates a reported symptom, not its cause. Before scheduler/causal drilldown, establish the target thread from independent evidence; retain explicit user windows and existing Trace supplementation. Only proven chain evidence supplies root causes; nearby work remains background."

// Shared exploration/final-writing guidance for the parser-defined source axis.
// Unit conversion does not grant cross-capture or source-to-canonical alignment.
const TraceJankClockContract = "For parser-recognized jank_event_sync metadata, start_ts/end_ts (normalized as start_ts_ns/end_ts_ns) are nanoseconds on the same source Trace time axis: source_trace_clock requires only division by 1,000,000,000 to obtain seconds, not timezone, UTC or calendar alignment. The header timestamp is report emission time and need not equal either payload endpoint; the payload duration is not the marker's B/E span duration. If a composite query uses an independently mapped canonical axis, apply only its existing declared source-to-canonical mapping. Do not infer an offset from numerical proximity or a delayed reporting header. Legacy unverified receipts retain their old parser status and are not upgraded by this teaching. This field-specific contract does not align arbitrary external timestamps or different captures."
