package tracequery

// Rebuilt on each read: consumers cannot mutate shared descriptors or nested
// slices. Composite rows reference existing views, not cloned metric contracts.
func capabilityViewDescriptors() []ViewCapability {
	formats := []string{"trace_text", "perf_trace_text", "tracebundle", "native_trace", "native_perf", "gzip", "zip"}
	row := func(name, summary string, objects, metrics, components []string, limitation string) ViewCapability {
		return ViewCapability{name, summary, objects, append([]string(nil), formats...), metrics, components, []string{limitation}}
	}
	windowMetrics := []string{"event_inventory", "scheduler_states", "cpu_occupancy", "scheduler_concurrency", "cpu_pressure", "cpu_frequency", "cpu_constraints", "compute_supply", "blocked_reasons", "sched_accounting", "io_request_latency", "io_inflight", "file_io", "page_cache", "io_pressure", "interrupt_activity", "workqueue", "dma_fence", "trace_spans", "track_spans", "trace_instants", "trace_counters", "counter_deltas", "runtime_resources", "plugin_inventory", "perf_samples", "state_churn", "vsync_inventory"}
	return []ViewCapability{
		row("event_search", "Literal event discovery with separate matched and emitted counts.", []string{"artifact", "event", "thread", "CPU"}, []string{"event_inventory", "reported_jank", "native_protocol_fields", "runtime_resources", "vsync_inventory"}, nil, "Display limit is not enumeration coverage; raw inventory does not prove a measured duration or dependency."),
		row("window_sweep", "Streaming event-density buckets and advisory follow-up windows.", []string{"artifact", "time bucket", "thread"}, []string{"event_density"}, nil, "Density identifies where to inspect, not a root cause; bucket width and scan coverage are reported separately."),
		row("span_window", "Locate complete synchronous or asynchronous named spans.", []string{"span", "thread", "process"}, []string{"trace_spans"}, nil, "Unmatched starts do not prove duration; async and process ownership need their exact identity."),
		row("frame_window", "Locate frame-like span windows.", []string{"frame candidate", "thread", "process"}, []string{"frame_spans"}, nil, "A frame-like name or duration alone does not prove jank, a deadline, or a frame identity join."),
		row("render_pipeline", "Summarize measured frame/render phase spans.", []string{"frame phase", "thread"}, []string{"render_phases"}, nil, "Phase recognition is not a cross-thread causal relation or GPU execution proof."),
		row("frame_timeline", "Frame-phase intervals with typed role and source boundaries.", []string{"frame phase", "thread", "process"}, []string{"frame_timeline", "frame_flow"}, nil, "Expected/actual/GPU labels retain their source-specific authority; phase order is not causal proof."),
		row("frame_flow", "Frame-phase ordering and published relation kinds.", []string{"frame phase", "thread"}, []string{"frame_timeline", "frame_flow"}, []string{"frame_timeline"}, "Sorted-span adjacency is temporal_sequence with causality_unproven, not an invented call/wakeup edge."),
		row("thread_timeline", "Thread scheduler-state intervals in a selected scope.", []string{"thread incarnation"}, []string{"scheduler_states"}, nil, "Missing transitions and identity discontinuities remain coverage limits; scheduler IO classification is not device attribution."),
		row("window_stats", "Per-window scheduler, IO, resource and sample summaries.", []string{"thread", "process", "CPU", "resource", "artifact"}, windowMetrics, nil, "Each optional family needs its own evidence; cross-thread sums, wall time and complete-pair populations have distinct denominators."),
		row("perf_stats", "CPU sample counts and independent event/weight cohorts.", []string{"sample cohort", "thread incarnation", "symbol", "DSO", "callchain"}, []string{"perf_samples"}, nil, "Sampling weight is not elapsed execution time; an unresolved IP or callchain is not source-call proof."),
		row("perf_timeline", "Bucketed CPU sample counts and cohort weights.", []string{"sample cohort", "time bucket"}, []string{"perf_samples", "perf_timeline"}, nil, "Different event/weight units or unaligned sources cannot share a denominator."),
		row("trace_perf_bundle", "Combine trace analysis with role-scoped sample context.", []string{"thread", "window", "sample cohort"}, []string{"scheduler_states", "root_attribution", "wakeup_relations", "perf_samples"}, []string{"window_stats", "wakeup_chain", "root_cause_rank", "perf_stats"}, "Only independently admitted and aligned components are present; a bundle never repairs missing causal evidence."),
		row("scheduler_latency_stats", "Runnable scheduling-delay distribution and bounded interval examples.", []string{"thread incarnation", "CPU"}, []string{"scheduler_latency"}, nil, "Wake-to-run or preempt-to-run runnable delay is not the preceding sleep/blocked interval."),
		row("ipc_graph", "Binder transaction relations with send/receive and call semantics.", []string{"binder transaction", "sender", "receiver"}, []string{"binder_relations"}, nil, "Oneway, unknown destination and unresolved transaction identities do not establish synchronous blocking."),
		row("wakeup_chain", "Time-consistent scheduler wakeup dependencies and state accounts.", []string{"target thread", "waker thread", "selected window"}, []string{"wakeup_relations", "scheduler_states"}, []string{"window_stats"}, "A recorded waker edge does not by itself explain its mechanism; expansion, coverage and attribution are separately bounded."),
		row("root_cause_rank", "Typed ranked attribution candidates with separate raw-state context.", []string{"target thread", "candidate", "rank board"}, []string{"root_attribution", "scheduler_states", "perf_samples"}, []string{"wakeup_chain", "window_stats"}, "Rank/attribution is not guaranteed removable latency; background or target symptoms must keep their published role and scope."),
		row("frame_root_cause_bundle", "Frame-window trace analysis with shared component provenance.", []string{"target thread", "frame window", "candidate"}, []string{"root_attribution", "frame_timeline", "blocking_candidates", "wakeup_relations", "perf_samples"}, []string{"wakeup_chain", "frame_timeline", "root_cause_rank", "critical_blocking_calls", "window_stats"}, "Sub-results retain their own required evidence, quantities and coverage; no whole-capture or deadline proof is implied."),
		row("critical_blocking_calls", "Measured blocking candidates and visible peer-state context.", []string{"thread", "candidate span", "peer"}, []string{"blocking_candidates"}, nil, "Caller/span classification is not waited-object ownership or a proven device bottleneck."),
		row("interaction_stats", "Directional wakeup and binder peer interaction counts.", []string{"target thread", "peer", "direction"}, []string{"interactions"}, nil, "Interaction counts are not elapsed duration or causal strength."),
		row("recipe", "Compose existing views for a selected analysis recipe.", []string{"target", "span", "selected window"}, []string{"evidence_composition"}, []string{"event_search", "span_window", "window_stats", "scheduler_latency_stats", "wakeup_chain", "ipc_graph", "root_cause_rank", "critical_blocking_calls", "frame_window", "render_pipeline", "frame_timeline", "frame_flow", "frame_root_cause_bundle"}, "The recipe determines the subset; it does not require one universal workflow or upgrade component evidence."),
		row("evidence_pack", "Publish line-backed findings from selected trace views.", []string{"target", "selected window", "evidence fact"}, []string{"evidence_composition"}, []string{"wakeup_chain", "window_stats", "ipc_graph", "scheduler_latency_stats", "critical_blocking_calls", "frame_root_cause_bundle"}, "A pack is evidence organization, not a new measurement or permission to bridge unrelated sources."),
	}
}
