package tracequery

// Event JSON-surface pin (P4 side-table refactor, trace_query_perf_parse_
// audit_20260703.md). The flat 140-field Event was reshaped into a slim core
// plus 8 kind-specific embedded-pointer side tables; the LLM-facing JSON
// surface (event_search rows, EvidencePack payloads) MUST stay byte-identical
// to the historical flat struct. The goldens below were generated by
// marshaling the PRE-refactor flat Event with the same tag-derived fill.
//
// Coverage, precisely: for the field kinds the fill knows (string, int/int32/
// int64, float64, bool, []int, *bool) this fails on any drift in key order,
// key names, omitempty behavior, or nil-group handling. A field of any OTHER
// kind cannot slip past as a silently-unfilled zero value (the []string
// double-green loophole): the fill fatals on unhandled kinds, and the
// serializable-leaf count is pinned at eventSerializableLeafCount. If you add
// a new Event field: extend the fill's kind switch if the kind is new, bump
// the leaf count, and extend the golden deliberately (insert the new key at
// the position its struct slot dictates) — never regenerate the golden
// blindly from the current code.

import (
	"encoding/json"
	"hash/crc32"
	"reflect"
	"strings"
	"testing"
	"unsafe"
)

// eventSerializableLeafCount pins the number of json-serializable leaf fields
// reachable from Event (json:"-" fields excluded): the historical flat struct
// had 140 fields of which 3 were json:"-".
const eventSerializableLeafCount = 137

// eventFillByJSONTag deterministically fills every leaf field reachable from
// v (allocating anonymous embedded struct pointers) with a value derived ONLY
// from the field's json tag — the invariant that survives struct reshapes, so
// pre- and post-refactor fills produce the same logical event. It returns the
// number of serializable leaves filled and fails the test on any field kind
// it does not know how to fill — a silently-zero leaf would make the golden
// comparison vacuously green for that field.
func eventFillByJSONTag(t *testing.T, v reflect.Value) int {
	t.Helper()
	typ := v.Type()
	leaves := 0
	for i := 0; i < typ.NumField(); i++ {
		f := typ.Field(i)
		fv := v.Field(i)
		if f.Anonymous {
			if fv.Kind() == reflect.Ptr {
				if fv.IsNil() {
					fv.Set(reflect.New(f.Type.Elem()))
				}
				leaves += eventFillByJSONTag(t, fv.Elem())
			} else if fv.Kind() == reflect.Struct {
				leaves += eventFillByJSONTag(t, fv)
			}
			continue
		}
		tag := strings.Split(f.Tag.Get("json"), ",")[0]
		if tag != "-" {
			leaves++
		}
		if tag == "" || tag == "-" {
			tag = f.Name
		}
		seed := int64(crc32.ChecksumIEEE([]byte(tag))%9000 + 1000)
		switch fv.Kind() {
		case reflect.String:
			fv.SetString(tag)
		case reflect.Int, reflect.Int32, reflect.Int64:
			fv.SetInt(seed)
		case reflect.Float64:
			fv.SetFloat(float64(seed) + 0.25)
		case reflect.Bool:
			fv.SetBool(true)
		case reflect.Slice:
			if f.Type.Elem().Kind() != reflect.Int {
				t.Fatalf("eventFillByJSONTag: field %s.%s has unhandled slice element kind %s — extend the fill (and the golden) deliberately, a zero-filled leaf would pass the golden vacuously", typ.Name(), f.Name, f.Type.Elem().Kind())
			}
			fv.Set(reflect.ValueOf([]int{int(seed), int(seed) + 1}))
		case reflect.Ptr:
			if f.Type.Elem().Kind() != reflect.Bool {
				t.Fatalf("eventFillByJSONTag: field %s.%s has unhandled pointer element kind %s — extend the fill (and the golden) deliberately", typ.Name(), f.Name, f.Type.Elem().Kind())
			}
			b := true
			fv.Set(reflect.ValueOf(&b))
		default:
			t.Fatalf("eventFillByJSONTag: field %s.%s has unhandled kind %s — extend the fill (and the golden) deliberately, a zero-filled leaf would pass the golden vacuously", typ.Name(), f.Name, fv.Kind())
		}
	}
	return leaves
}

func TestEventJSONSurfaceGolden(t *testing.T) {
	var ev Event
	if leaves := eventFillByJSONTag(t, reflect.ValueOf(&ev).Elem()); leaves != eventSerializableLeafCount {
		t.Fatalf("Event has %d serializable leaf fields, pinned %d — a field was added or removed; extend fill + golden + this count deliberately", leaves, eventSerializableLeafCount)
	}
	full, err := json.MarshalIndent(ev, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if string(full) != eventJSONGoldenFull {
		t.Errorf("fully-populated Event JSON drifted from the pre-P4 flat surface:\n got: %s\nwant: %s", full, eventJSONGoldenFull)
	}
	viewJSON, err := json.MarshalIndent(EventView{Event: ev, Raw: "raw-line-text"}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if string(viewJSON) != eventJSONGoldenView {
		t.Errorf("EventView JSON drifted from the pre-P4 flat surface:\n got: %s\nwant: %s", viewJSON, eventJSONGoldenView)
	}
	sparse, err := json.MarshalIndent(Event{Line: 7, Ts: 100.5, Type: EventSchedSwitch, Name: "sched_switch", Comm: "app", PID: 42, PrevComm: "prev", PrevPID: 41, NextComm: "next", NextPID: 43}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if string(sparse) != eventJSONGoldenSparse {
		t.Errorf("sparse Event (nil side tables) JSON drifted — nil groups must emit exactly what all-zero omitempty fields emitted:\n got: %s\nwant: %s", sparse, eventJSONGoldenSparse)
	}
}

// TestEventCoreSizeRatchet pins the P4 win: the core Event shrank from 1736
// to 688 bytes (side tables are per-kind allocations). This is a ratchet —
// lowering is welcome, raising it back must be a deliberate, reviewed act
// (add to a side table instead of the core when the field is kind-specific).
func TestEventCoreSizeRatchet(t *testing.T) {
	const ceiling = 688
	if size := unsafe.Sizeof(Event{}); size > ceiling {
		t.Fatalf("Event core is %d bytes, over the P4 ratchet ceiling %d. Kind-specific payloads belong in a side-table group (*PerfFields et al.), not the core struct every sched_switch pays for.", size, ceiling)
	}
}

const eventJSONGoldenFull = `{
  "line": 1190,
  "ts": 2435.25,
  "cpu": 5310,
  "type": "type",
  "name": "name",
  "comm": "comm",
  "pid": 6653,
  "tgid": 2085,
  "prev_comm": "prev_comm",
  "prev_pid": 3710,
  "prev_prio": 4583,
  "prev_prio_class": "prev_prio_class",
  "prev_state": "prev_state",
  "next_comm": "next_comm",
  "next_pid": 6098,
  "next_prio": 6795,
  "next_prio_class": "next_prio_class",
  "next_info": "next_info",
  "next_info_affinity": "next_info_affinity",
  "next_info_allowed_cpus": [
    3269,
    3270
  ],
  "next_info_load": 5832,
  "next_info_group": 2539,
  "next_info_restricted": true,
  "next_info_expel": 1388,
  "next_info_cgid": 4758,
  "cgroup": "cgroup",
  "wakee_comm": "wakee_comm",
  "wakee_pid": 3439,
  "wakee_prio": 4761,
  "wakee_prio_class": "wakee_prio_class",
  "target_cpu": 6859,
  "constraint_comm": "constraint_comm",
  "constraint_pid": 8406,
  "constraint_kind": "constraint_kind",
  "constraint_policy": "constraint_policy",
  "constraint_cpu": 7181,
  "constraint_orig_cpu": 8645,
  "constraint_dest_cpu": 4196,
  "allowed_cpus_text": "allowed_cpus_text",
  "allowed_cpus": [
    3961,
    3962
  ],
  "cpuset": "cpuset",
  "state": 5011,
  "frequency": 2403,
  "frequency_min": 9351,
  "frequency_max": 9606,
  "cpu_for_field": 2782,
  "cpu_for_field_valid": true,
  "clock_name": "clock_name",
  "reason": "reason",
  "io_wait": 7972,
  "sched_stat_kind": "sched_stat_kind",
  "sched_stat_comm": "sched_stat_comm",
  "sched_stat_pid": 9416,
  "sched_stat_delay_ns": 5047,
  "sched_stat_runtime_ns": 7113,
  "sched_stat_vruntime_ns": 9819,
  "span_action": "span_action",
  "span_pid": 2593,
  "span_name": "span_name",
  "span_value": "span_value",
  "binder_transaction_id": 2589,
  "binder_dest_proc": 6591,
  "binder_dest_thread": 6405,
  "binder_reply": 4924,
  "binder_flags": "binder_flags",
  "binder_code": "binder_code",
  "binder_debug_id": 3800,
  "binder_data_size": 9469,
  "binder_offsets_size": 7466,
  "binder_extra_size": 1911,
  "binder_lock_tag": "binder_lock_tag",
  "block_dev": "block_dev",
  "block_op": "block_op",
  "block_sector": 1107,
  "block_len": 8025,
  "block_error": "block_error",
  "block_src_dev": "block_src_dev",
  "block_src_sector": 7184,
  "irq_name": "irq_name",
  "irq_id": 4565,
  "ipi_target_mask": "ipi_target_mask",
  "ipi_target_cpus": [
    4204,
    4205
  ],
  "memory_kind": "memory_kind",
  "subsystem_kind": "subsystem_kind",
  "resource_path": "resource_path",
  "resource_op": "resource_op",
  "resource_latency_ms": 5489.25,
  "resource_bytes": 1332,
  "resource_address": "resource_address",
  "resource_callstack": "resource_callstack",
  "fs_dev": "fs_dev",
  "inode": "inode",
  "parent_inode": "parent_inode",
  "entry_name": "entry_name",
  "file_offset": 3671,
  "file_len": 2610,
  "file_rw": "file_rw",
  "file_ret": 5586,
  "file_size": 1836,
  "plugin_domain": "plugin_domain",
  "plugin_event_name": "plugin_event_name",
  "plugin_metric": "plugin_metric",
  "plugin_value": "plugin_value",
  "plugin_category": "plugin_category",
  "perf_pid": 1015,
  "perf_tid": 9203,
  "perf_comm": "perf_comm",
  "perf_period": 7247,
  "perf_event": "perf_event",
  "perf_symbol": "perf_symbol",
  "perf_dso": "perf_dso",
  "perf_ip": "perf_ip",
  "perf_addr": "perf_addr",
  "perf_sample_id": "perf_sample_id",
  "perf_stream_id": "perf_stream_id",
  "perf_raw_weight": 7429,
  "perf_data_src": "perf_data_src",
  "perf_transaction": "perf_transaction",
  "perf_phys_addr": "perf_phys_addr",
  "perf_cgroup_id": "perf_cgroup_id",
  "perf_data_page_size": 1175,
  "perf_code_page_size": 3673,
  "perf_raw_size": 2501,
  "perf_branch_count": 6955,
  "perf_user_regs_abi": "perf_user_regs_abi",
  "perf_user_regs_count": 7714,
  "perf_user_stack_size": 6151,
  "perf_aux_size": 7549,
  "perf_callchain": "perf_callchain",
  "perf_source": "perf_source",
  "perf_sample_kind": "perf_sample_kind",
  "perf_symbolization_status": "perf_symbolization_status",
  "perf_clock": "perf_clock",
  "perf_cpu_known": true,
  "perf_clock_confidence": "perf_clock_confidence",
  "perf_callchain_status": "perf_callchain_status",
  "field_text": "field_text"
}`

const eventJSONGoldenView = `{
  "line": 1190,
  "ts": 2435.25,
  "cpu": 5310,
  "type": "type",
  "name": "name",
  "comm": "comm",
  "pid": 6653,
  "tgid": 2085,
  "prev_comm": "prev_comm",
  "prev_pid": 3710,
  "prev_prio": 4583,
  "prev_prio_class": "prev_prio_class",
  "prev_state": "prev_state",
  "next_comm": "next_comm",
  "next_pid": 6098,
  "next_prio": 6795,
  "next_prio_class": "next_prio_class",
  "next_info": "next_info",
  "next_info_affinity": "next_info_affinity",
  "next_info_allowed_cpus": [
    3269,
    3270
  ],
  "next_info_load": 5832,
  "next_info_group": 2539,
  "next_info_restricted": true,
  "next_info_expel": 1388,
  "next_info_cgid": 4758,
  "cgroup": "cgroup",
  "wakee_comm": "wakee_comm",
  "wakee_pid": 3439,
  "wakee_prio": 4761,
  "wakee_prio_class": "wakee_prio_class",
  "target_cpu": 6859,
  "constraint_comm": "constraint_comm",
  "constraint_pid": 8406,
  "constraint_kind": "constraint_kind",
  "constraint_policy": "constraint_policy",
  "constraint_cpu": 7181,
  "constraint_orig_cpu": 8645,
  "constraint_dest_cpu": 4196,
  "allowed_cpus_text": "allowed_cpus_text",
  "allowed_cpus": [
    3961,
    3962
  ],
  "cpuset": "cpuset",
  "state": 5011,
  "frequency": 2403,
  "frequency_min": 9351,
  "frequency_max": 9606,
  "cpu_for_field": 2782,
  "cpu_for_field_valid": true,
  "clock_name": "clock_name",
  "reason": "reason",
  "io_wait": 7972,
  "sched_stat_kind": "sched_stat_kind",
  "sched_stat_comm": "sched_stat_comm",
  "sched_stat_pid": 9416,
  "sched_stat_delay_ns": 5047,
  "sched_stat_runtime_ns": 7113,
  "sched_stat_vruntime_ns": 9819,
  "span_action": "span_action",
  "span_pid": 2593,
  "span_name": "span_name",
  "span_value": "span_value",
  "binder_transaction_id": 2589,
  "binder_dest_proc": 6591,
  "binder_dest_thread": 6405,
  "binder_reply": 4924,
  "binder_flags": "binder_flags",
  "binder_code": "binder_code",
  "binder_debug_id": 3800,
  "binder_data_size": 9469,
  "binder_offsets_size": 7466,
  "binder_extra_size": 1911,
  "binder_lock_tag": "binder_lock_tag",
  "block_dev": "block_dev",
  "block_op": "block_op",
  "block_sector": 1107,
  "block_len": 8025,
  "block_error": "block_error",
  "block_src_dev": "block_src_dev",
  "block_src_sector": 7184,
  "irq_name": "irq_name",
  "irq_id": 4565,
  "ipi_target_mask": "ipi_target_mask",
  "ipi_target_cpus": [
    4204,
    4205
  ],
  "memory_kind": "memory_kind",
  "subsystem_kind": "subsystem_kind",
  "resource_path": "resource_path",
  "resource_op": "resource_op",
  "resource_latency_ms": 5489.25,
  "resource_bytes": 1332,
  "resource_address": "resource_address",
  "resource_callstack": "resource_callstack",
  "fs_dev": "fs_dev",
  "inode": "inode",
  "parent_inode": "parent_inode",
  "entry_name": "entry_name",
  "file_offset": 3671,
  "file_len": 2610,
  "file_rw": "file_rw",
  "file_ret": 5586,
  "file_size": 1836,
  "plugin_domain": "plugin_domain",
  "plugin_event_name": "plugin_event_name",
  "plugin_metric": "plugin_metric",
  "plugin_value": "plugin_value",
  "plugin_category": "plugin_category",
  "perf_pid": 1015,
  "perf_tid": 9203,
  "perf_comm": "perf_comm",
  "perf_period": 7247,
  "perf_event": "perf_event",
  "perf_symbol": "perf_symbol",
  "perf_dso": "perf_dso",
  "perf_ip": "perf_ip",
  "perf_addr": "perf_addr",
  "perf_sample_id": "perf_sample_id",
  "perf_stream_id": "perf_stream_id",
  "perf_raw_weight": 7429,
  "perf_data_src": "perf_data_src",
  "perf_transaction": "perf_transaction",
  "perf_phys_addr": "perf_phys_addr",
  "perf_cgroup_id": "perf_cgroup_id",
  "perf_data_page_size": 1175,
  "perf_code_page_size": 3673,
  "perf_raw_size": 2501,
  "perf_branch_count": 6955,
  "perf_user_regs_abi": "perf_user_regs_abi",
  "perf_user_regs_count": 7714,
  "perf_user_stack_size": 6151,
  "perf_aux_size": 7549,
  "perf_callchain": "perf_callchain",
  "perf_source": "perf_source",
  "perf_sample_kind": "perf_sample_kind",
  "perf_symbolization_status": "perf_symbolization_status",
  "perf_clock": "perf_clock",
  "perf_cpu_known": true,
  "perf_clock_confidence": "perf_clock_confidence",
  "perf_callchain_status": "perf_callchain_status",
  "field_text": "field_text",
  "raw": "raw-line-text"
}`

const eventJSONGoldenSparse = `{
  "line": 7,
  "ts": 100.5,
  "type": "sched_switch",
  "name": "sched_switch",
  "comm": "app",
  "pid": 42,
  "prev_comm": "prev",
  "prev_pid": 41,
  "next_comm": "next",
  "next_pid": 43
}`
