package hitraceconv

import (
	"fmt"
	"strings"
)

// LocalizeConvertMessage keeps converter core caveats machine-stable internally
// while letting CLI/REPL surfaces follow the user's display language.
func LocalizeConvertMessage(lang, message string) string {
	if !convertUseZh(lang) {
		return message
	}
	return localizeConvertMessageZh(message)
}

func convertUseZh(lang string) bool {
	return !strings.EqualFold(strings.TrimSpace(lang), "en")
}

func localizeConvertMessageZh(message string) string {
	trimmed := strings.TrimSpace(message)
	lower := strings.ToLower(trimmed)
	var perfDataCount, perfTraceCount, officialCount, rawCount int
	switch {
	case scanConvertMessage(trimmed, "extracted %d HIPERF_DATA standalone perf.data artifact(s) and generated %d normalized .perftrace artifact(s) through Codrax raw perf.data fallback", &perfDataCount, &perfTraceCount) == 2:
		return fmt.Sprintf("已抽取 %d 个 HIPERF_DATA standalone perf.data artifact，并通过 Codrax raw perf.data fallback 生成 %d 个标准化 .perftrace artifact", perfDataCount, perfTraceCount)
	case scanConvertMessage(trimmed, "extracted %d HIPERF_DATA standalone perf.data artifact(s) and generated %d normalized .perftrace artifact(s) through the official perf adapter", &perfDataCount, &perfTraceCount) == 2:
		return fmt.Sprintf("已抽取 %d 个 HIPERF_DATA standalone perf.data artifact，并通过官方 perf adapter 生成 %d 个标准化 .perftrace artifact", perfDataCount, perfTraceCount)
	case scanConvertMessage(trimmed, "extracted %d HIPERF_DATA standalone perf.data artifact(s) and generated %d normalized .perftrace artifact(s) through mixed providers (official=%d raw=%d)", &perfDataCount, &perfTraceCount, &officialCount, &rawCount) == 4:
		return fmt.Sprintf("已抽取 %d 个 HIPERF_DATA standalone perf.data artifact，并通过混合 provider 生成 %d 个标准化 .perftrace artifact（official=%d raw=%d）", perfDataCount, perfTraceCount, officialCount, rawCount)
	case scanConvertMessage(trimmed, "extracted %d HIPERF_DATA standalone perf.data artifact(s); raw perf.data is preserved as sidecar and still needs official parser conversion to .perftrace for trace_query sample aggregation", &perfDataCount) == 1:
		return fmt.Sprintf("已抽取 %d 个 HIPERF_DATA standalone perf.data artifact；raw perf.data 已作为 sidecar 保留，仍需要官方 parser 转成 .perftrace 后 trace_query 才能聚合 CPU sample", perfDataCount)
	case strings.Contains(lower, "hiperf_data perf.data extracted; no official hiperf_host/hiperf adapter was configured or found") && strings.Contains(lower, "fell back to raw perf.data parser"):
		return "已抽取 HIPERF_DATA perf.data；未配置或未发现官方 hiperf_host/hiperf adapter；已回退到 Codrax raw perf.data parser"
	case strings.Contains(lower, "hiperf_data perf.data extracted; no official hiperf_host/hiperf adapter was configured or found"):
		return "已抽取 HIPERF_DATA perf.data；未配置或未发现官方 hiperf_host/hiperf adapter"
	case strings.Contains(lower, "raw perf.data sidecar preserved; normalized .perftrace was generated"):
		return "raw perf.data sidecar 已保留；已生成标准化 .perftrace，trace_query 可用于 CPU sample 聚合"
	case strings.Contains(lower, "raw perf.data sidecar extracted; run an official hiperf/simpleperf adapter"):
		return "已抽取 raw perf.data sidecar；需要运行官方 hiperf/simpleperf adapter 生成 .perftrace 后，trace_query 才能聚合 CPU sample"
	case strings.Contains(lower, "trace_streamer was not discovered; auto trace+perf conversion will use"):
		return "未发现 trace_streamer；auto 模式下 trace+perf 会使用内置 raw trace 解析和 standalone perf 兜底"
	case strings.Contains(lower, "trace_streamer was not discovered; auto trace conversion will use"):
		return "未发现 trace_streamer；auto 模式下会使用内置 raw trace 解析器"
	case strings.Contains(lower, "trace_streamer was not discovered; selected sql trace conversion cannot produce systrace"):
		return "未发现 trace_streamer；当前显式选择的 SQL trace 转换无法生成 systrace，且不会自动退化"
	case strings.Contains(lower, "systrace output was not produced because selected trace_streamer/sqlite trace conversion"):
		return "未生成 systrace，因为当前显式选择的 trace_streamer/SQLite 转换没有产出 trace_query 可用行，且不会自动退化"
	case strings.Contains(lower, "trace+perf auto conversion uses trace_streamer/sqlite first"):
		return "trace+perf auto 转换会优先使用 trace_streamer/SQLite；SQL 不可用或失败时退回内置 raw trace 解析；显式 trace engine 不退化"
	case strings.Contains(lower, "generated by codrax raw perf.data fallback"):
		return "由 Codrax raw perf.data fallback 生成；存在已保存的 hiperf 符号 section 时会使用其中的函数名，否则保留 IP/DSO 级上下文"
	case strings.Contains(lower, "systrace output was not produced because"):
		return strings.Replace(trimmed, "systrace output was not produced because", "未生成 systrace：", 1)
	case strings.Contains(lower, "built-in sys binary parser could not render the trace body"):
		return strings.Replace(trimmed, "built-in sys binary parser could not render the trace body", "内置 sys binary parser 无法渲染 trace body", 1)
	case strings.Contains(lower, "openharmony profiler/session container was detected, but no renderable systrace"):
		return "检测到 OpenHarmony profiler/session container，但没有可渲染的 systrace 文本行或 sidecar artifact"
	case strings.Contains(lower, "openharmony profiler/session container was detected, but only sidecar artifacts"):
		return "检测到 OpenHarmony profiler/session container，但只生成了 sidecar artifact"
	case strings.Contains(lower, "raw fallback parsed perf feature metadata:"):
		return strings.Replace(trimmed, "raw fallback parsed perf feature metadata:", "raw fallback 已解析 perf feature 元数据：", 1)
	case strings.Contains(lower, "raw fallback detected hiperf_files_unistack_table"):
		return "raw fallback 检测到 HIPERF_FILES_UNISTACK_TABLE；未通过官方 hiperf report 流程前，不展开 deduplicated stack id"
	case strings.Contains(lower, "deduplicated stack ids are not expanded"):
		return "检测到 deduplicated stack table；raw fallback 不展开 stack id，完整调用栈请优先使用官方 hiperf report"
	case strings.Contains(lower, "no capture-level trace/perf clock map is available"):
		return "没有 capture 级 trace/perf 时钟映射；trace_query 会把时间重叠作为辅助证据，除非存在 calibrated 映射"
	case strings.Contains(lower, "raw fallback skipped non-causal sample payload field"):
		return strings.Replace(trimmed, "raw fallback skipped non-causal sample payload field(s):", "raw fallback 已跳过非因果 sample payload 字段：", 1)
	case strings.Contains(lower, "raw perf.data fallback disabled by perf parser mode"):
		return "raw perf.data fallback 已被 perf parser 模式禁用"
	case strings.Contains(lower, "raw perf.data fallback could not parse"):
		return strings.Replace(trimmed, "raw perf.data fallback could not parse", "raw perf.data fallback 无法解析", 1)
	case strings.Contains(lower, "official hiperf adapter skipped because raw perf parser mode was requested"):
		return "已请求 raw perf parser 模式，因此跳过官方 hiperf adapter"
	case strings.Contains(lower, "official hiperf adapter") && strings.Contains(lower, "failed"):
		return strings.Replace(trimmed, "official hiperf adapter", "官方 hiperf adapter", 1)
	case strings.Contains(lower, "official hiperf adapter") && strings.Contains(lower, "produced unreadable protobuf"):
		return strings.Replace(trimmed, "official hiperf adapter", "官方 hiperf adapter", 1)
	case strings.Contains(lower, "fell back to raw perf.data parser"):
		return strings.Replace(trimmed, "fell back to raw perf.data parser", "已回退到 raw perf.data parser", 1)
	default:
		return trimmed
	}
}

func scanConvertMessage(s, format string, args ...any) int {
	n, _ := fmt.Sscanf(s, format, args...)
	return n
}
