package hitraceconv

import (
	"bufio"
	"context"
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

const (
	rawPerfDataAdapterVersion = converterVersion + "+raw-perfdata"
	perfMagic2                = "PERFILE2"

	perfRecordMmap   = 1
	perfRecordComm   = 3
	perfRecordSample = 9
	perfRecordMmap2  = 10

	perfSampleIP         = 1 << 0
	perfSampleTID        = 1 << 1
	perfSampleTime       = 1 << 2
	perfSampleAddr       = 1 << 3
	perfSampleRead       = 1 << 4
	perfSampleCallchain  = 1 << 5
	perfSampleID         = 1 << 6
	perfSampleCPU        = 1 << 7
	perfSamplePeriod     = 1 << 8
	perfSampleStreamID   = 1 << 9
	perfSampleRaw        = 1 << 10
	perfSampleIdentifier = 1 << 16
)

const rawPerfSupportedSampleBits = perfSampleIP | perfSampleTID | perfSampleTime | perfSampleAddr | perfSampleCallchain | perfSampleID | perfSampleCPU | perfSamplePeriod | perfSampleStreamID | perfSampleIdentifier

type rawPerfFileHeader struct {
	AttrSize    uint64
	AttrsOffset uint64
	AttrsSize   uint64
	DataOffset  uint64
	DataSize    uint64
}

type rawPerfSample struct {
	IP        uint64
	PID       int
	TID       int
	TimeNS    uint64
	CPU       int
	CPUValid  bool
	Period    uint64
	ID        uint64
	Callchain []uint64
}

type rawPerfMapping struct {
	PID   int
	TID   int
	Addr  uint64
	Len   uint64
	Pgoff uint64
	Path  string
}

type rawPerfData struct {
	SampleType uint64
	EventName  string
	Threads    map[int]string
	Mappings   []rawPerfMapping
	Samples    []rawPerfSample
	Caveats    []string
}

func rawPerfParserAllowed(opts Options) bool {
	mode := normalizePerfParserMode(opts.PerfParser)
	return mode == "raw" || mode == "fallback" || mode == "auto" || mode == ""
}

func rawPerfParserRequired(opts Options) bool {
	mode := normalizePerfParserMode(opts.PerfParser)
	return mode == "raw" || mode == "fallback"
}

func normalizePerfParserMode(mode string) string {
	return strings.ToLower(strings.TrimSpace(mode))
}

func validatePerfParserMode(mode string) error {
	switch normalizePerfParserMode(mode) {
	case "", "auto", "official", "raw", "fallback":
		return nil
	default:
		return fmt.Errorf("unsupported perf parser mode %q; use auto, official, or raw", mode)
	}
}

func hasRawPerfDataMagic(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	var magic [8]byte
	if _, err := io.ReadFull(f, magic[:]); err != nil {
		return false
	}
	return string(magic[:]) == perfMagic2
}

func maybeConvertRawPerfData(ctx context.Context, opts Options, perfPath, perfTracePath string) (Artifact, string, error) {
	if !rawPerfParserAllowed(opts) {
		return Artifact{}, "raw perf.data fallback disabled by perf parser mode", nil
	}
	if err := ensureOutputDoesNotExist(perfTracePath); err != nil {
		return Artifact{}, "", err
	}
	if err := ConvertRawPerfDataFileToPerfTrace(ctx, perfPath, perfTracePath); err != nil {
		_ = os.Remove(perfTracePath)
		return Artifact{}, fmt.Sprintf("raw perf.data fallback could not parse %q (%v); .perftrace was not generated", perfPath, err), nil
	}
	info, err := os.Stat(perfTracePath)
	if err != nil {
		return Artifact{}, "", err
	}
	return Artifact{
		Type:      ArtifactPerfTrace,
		Path:      perfTracePath,
		Bytes:     info.Size(),
		Converter: rawPerfDataAdapterVersion,
		Caveats: []string{
			"generated by Codrax raw perf.data fallback; symbols are unsymbolized unless IP-only labels are sufficient",
		},
	}, "", nil
}

func ConvertRawPerfDataFileToPerfTrace(ctx context.Context, inputPath, outputPath string) error {
	if ctx == nil {
		ctx = context.Background()
	}
	data, err := readRawPerfData(ctx, inputPath)
	if err != nil {
		return err
	}
	if len(data.Samples) == 0 {
		return fmt.Errorf("raw perf.data contains no supported sample records")
	}
	if err := ensureOutputDoesNotExist(outputPath); err != nil {
		return err
	}
	out, err := os.OpenFile(outputPath, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	w := bufio.NewWriter(out)
	writeErr := writeRawPerfDataPerfTrace(ctx, w, data)
	flushErr := w.Flush()
	closeErr := out.Close()
	if writeErr != nil {
		_ = os.Remove(outputPath)
		return writeErr
	}
	if flushErr != nil {
		_ = os.Remove(outputPath)
		return flushErr
	}
	if closeErr != nil {
		_ = os.Remove(outputPath)
		return closeErr
	}
	return nil
}

func readRawPerfData(ctx context.Context, path string) (rawPerfData, error) {
	f, err := os.Open(path)
	if err != nil {
		return rawPerfData{}, err
	}
	defer f.Close()
	header, err := readRawPerfHeader(f)
	if err != nil {
		return rawPerfData{}, err
	}
	sampleType, eventName, caveats, err := readRawPerfAttr(f, header)
	if err != nil {
		return rawPerfData{}, err
	}
	unsupported := sampleType &^ rawPerfSupportedSampleBits
	if unsupported != 0 {
		return rawPerfData{}, fmt.Errorf("unsupported sample_type bits 0x%x in raw fallback", unsupported)
	}
	out := rawPerfData{
		SampleType: sampleType,
		EventName:  eventName,
		Threads:    map[int]string{},
		Caveats:    caveats,
	}
	if _, err := f.Seek(int64(header.DataOffset), io.SeekStart); err != nil {
		return rawPerfData{}, err
	}
	remaining := int64(header.DataSize)
	for remaining > 0 {
		if err := ctx.Err(); err != nil {
			return rawPerfData{}, err
		}
		var hdr [8]byte
		if _, err := io.ReadFull(f, hdr[:]); err != nil {
			return rawPerfData{}, fmt.Errorf("read perf record header: %w", err)
		}
		typ := binary.LittleEndian.Uint32(hdr[0:4])
		size := int(binary.LittleEndian.Uint16(hdr[6:8]))
		if size < len(hdr) || int64(size) > remaining {
			return rawPerfData{}, fmt.Errorf("invalid perf record size %d", size)
		}
		payload := make([]byte, size-len(hdr))
		if _, err := io.ReadFull(f, payload); err != nil {
			return rawPerfData{}, fmt.Errorf("read perf record payload: %w", err)
		}
		switch typ {
		case perfRecordComm:
			parseRawPerfComm(payload, out.Threads)
		case perfRecordMmap:
			if mapping, ok := parseRawPerfMmap(payload); ok {
				out.Mappings = append(out.Mappings, mapping)
			}
		case perfRecordMmap2:
			if mapping, ok := parseRawPerfMmap2(payload); ok {
				out.Mappings = append(out.Mappings, mapping)
			}
		case perfRecordSample:
			sample, ok := parseRawPerfSample(payload, sampleType)
			if ok {
				out.Samples = append(out.Samples, sample)
			}
		default:
		}
		remaining -= int64(size)
	}
	return out, nil
}

func readRawPerfHeader(r io.ReaderAt) (rawPerfFileHeader, error) {
	buf := make([]byte, 104)
	if _, err := r.ReadAt(buf, 0); err != nil {
		return rawPerfFileHeader{}, fmt.Errorf("read perf.data header: %w", err)
	}
	if string(buf[:8]) != perfMagic2 {
		return rawPerfFileHeader{}, fmt.Errorf("unsupported perf.data magic %q", string(buf[:8]))
	}
	size := binary.LittleEndian.Uint64(buf[8:16])
	if size < 80 {
		return rawPerfFileHeader{}, fmt.Errorf("unsupported perf.data header size %d", size)
	}
	return rawPerfFileHeader{
		AttrSize:    binary.LittleEndian.Uint64(buf[16:24]),
		AttrsOffset: binary.LittleEndian.Uint64(buf[24:32]),
		AttrsSize:   binary.LittleEndian.Uint64(buf[32:40]),
		DataOffset:  binary.LittleEndian.Uint64(buf[40:48]),
		DataSize:    binary.LittleEndian.Uint64(buf[48:56]),
	}, nil
}

func readRawPerfAttr(r io.ReaderAt, header rawPerfFileHeader) (sampleType uint64, eventName string, caveats []string, err error) {
	if header.AttrsOffset == 0 || header.AttrsSize == 0 {
		return 0, "", nil, fmt.Errorf("perf.data has no attrs section")
	}
	attrSize := header.AttrSize
	if attrSize == 0 || attrSize > header.AttrsSize {
		attrSize = header.AttrsSize
	}
	attr := make([]byte, attrSize)
	if _, err := r.ReadAt(attr, int64(header.AttrsOffset)); err != nil {
		return 0, "", nil, fmt.Errorf("read perf attrs: %w", err)
	}
	if len(attr) < 32 {
		return 0, "", nil, fmt.Errorf("perf attr too small: %d", len(attr))
	}
	config := binary.LittleEndian.Uint64(attr[8:16])
	sampleType = binary.LittleEndian.Uint64(attr[24:32])
	eventName = "config:0x" + strconv.FormatUint(config, 16)
	if attrSize < header.AttrsSize {
		caveats = append(caveats, "raw fallback used the first perf attr only; multi-event perf.data is degraded")
	}
	return sampleType, eventName, caveats, nil
}

func parseRawPerfComm(payload []byte, threads map[int]string) {
	if len(payload) < 8 {
		return
	}
	pid := int(binary.LittleEndian.Uint32(payload[0:4]))
	tid := int(binary.LittleEndian.Uint32(payload[4:8]))
	name := cString(payload[8:])
	if name == "" {
		return
	}
	threads[tid] = name
	if pid > 0 {
		threads[pid] = name
	}
}

func parseRawPerfMmap(payload []byte) (rawPerfMapping, bool) {
	if len(payload) < 32 {
		return rawPerfMapping{}, false
	}
	mapping := rawPerfMapping{
		PID:   int(binary.LittleEndian.Uint32(payload[0:4])),
		TID:   int(binary.LittleEndian.Uint32(payload[4:8])),
		Addr:  binary.LittleEndian.Uint64(payload[8:16]),
		Len:   binary.LittleEndian.Uint64(payload[16:24]),
		Pgoff: binary.LittleEndian.Uint64(payload[24:32]),
		Path:  cString(payload[32:]),
	}
	return mapping, mapping.Len > 0 && strings.TrimSpace(mapping.Path) != ""
}

func parseRawPerfMmap2(payload []byte) (rawPerfMapping, bool) {
	if len(payload) < 64 {
		return rawPerfMapping{}, false
	}
	mapping := rawPerfMapping{
		PID:   int(binary.LittleEndian.Uint32(payload[0:4])),
		TID:   int(binary.LittleEndian.Uint32(payload[4:8])),
		Addr:  binary.LittleEndian.Uint64(payload[8:16]),
		Len:   binary.LittleEndian.Uint64(payload[16:24]),
		Pgoff: binary.LittleEndian.Uint64(payload[24:32]),
		Path:  cString(payload[64:]),
	}
	return mapping, mapping.Len > 0 && strings.TrimSpace(mapping.Path) != ""
}

func parseRawPerfSample(payload []byte, sampleType uint64) (rawPerfSample, bool) {
	var sample rawPerfSample
	off := 0
	readU64 := func() (uint64, bool) {
		if off+8 > len(payload) {
			return 0, false
		}
		v := binary.LittleEndian.Uint64(payload[off : off+8])
		off += 8
		return v, true
	}
	readU32Pair := func() (uint32, uint32, bool) {
		if off+8 > len(payload) {
			return 0, 0, false
		}
		a := binary.LittleEndian.Uint32(payload[off : off+4])
		b := binary.LittleEndian.Uint32(payload[off+4 : off+8])
		off += 8
		return a, b, true
	}
	if sampleType&perfSampleIdentifier != 0 {
		v, ok := readU64()
		if !ok {
			return rawPerfSample{}, false
		}
		sample.ID = v
	}
	if sampleType&perfSampleIP != 0 {
		v, ok := readU64()
		if !ok {
			return rawPerfSample{}, false
		}
		sample.IP = v
	}
	if sampleType&perfSampleTID != 0 {
		pid, tid, ok := readU32Pair()
		if !ok {
			return rawPerfSample{}, false
		}
		sample.PID = int(pid)
		sample.TID = int(tid)
	}
	if sampleType&perfSampleTime != 0 {
		v, ok := readU64()
		if !ok {
			return rawPerfSample{}, false
		}
		sample.TimeNS = v
	}
	if sampleType&perfSampleAddr != 0 {
		if _, ok := readU64(); !ok {
			return rawPerfSample{}, false
		}
	}
	if sampleType&perfSampleID != 0 {
		v, ok := readU64()
		if !ok {
			return rawPerfSample{}, false
		}
		sample.ID = v
	}
	if sampleType&perfSampleStreamID != 0 {
		if _, ok := readU64(); !ok {
			return rawPerfSample{}, false
		}
	}
	if sampleType&perfSampleCPU != 0 {
		cpu, _, ok := readU32Pair()
		if !ok {
			return rawPerfSample{}, false
		}
		sample.CPU = int(cpu)
		sample.CPUValid = true
	}
	if sampleType&perfSamplePeriod != 0 {
		v, ok := readU64()
		if !ok {
			return rawPerfSample{}, false
		}
		sample.Period = v
	}
	if sampleType&perfSampleCallchain != 0 {
		nr, ok := readU64()
		if !ok || nr > 4096 {
			return rawPerfSample{}, false
		}
		for i := uint64(0); i < nr; i++ {
			v, ok := readU64()
			if !ok {
				return rawPerfSample{}, false
			}
			sample.Callchain = append(sample.Callchain, v)
		}
	}
	if sample.Period == 0 {
		sample.Period = 1
	}
	return sample, true
}

func writeRawPerfDataPerfTrace(ctx context.Context, w io.Writer, data rawPerfData) error {
	if _, err := io.WriteString(w, systraceHeader); err != nil {
		return err
	}
	for _, sample := range data.Samples {
		if err := ctx.Err(); err != nil {
			return err
		}
		tid := sample.TID
		if tid <= 0 {
			tid = sample.PID
		}
		if tid <= 0 {
			tid = 1
		}
		pid := sample.PID
		if pid <= 0 {
			pid = tid
		}
		comm := sanitizePerfTraceComm(firstNonEmpty(data.Threads[tid], fmt.Sprintf("tid%d", tid)))
		cpu := -1
		if sample.CPUValid {
			cpu = sample.CPU
		}
		ip := rawPerfIP(sample.IP)
		dso := rawPerfDSO(data.Mappings, sample)
		callchain := rawPerfCallchain(sample)
		ts := float64(sample.TimeNS) / 1e9
		if _, err := fmt.Fprintf(w, "%16s-%-6d (%5d) [%03d] .... %12.6f: perf_sample: cpu=%d pid=%d tid=%d thread_comm=%s period=%d event=%s symbol=%s dso=%s ip=%s callchain=%s source=raw_perfdata_fallback symbolization_status=unsymbolized clock=perf_data\n",
			comm, tid, pid, rawPerfHeaderCPU(cpu), ts, cpu, pid, tid, quoteTraceValue(comm), sample.Period, quoteTraceValue(data.EventName), quoteTraceValue(ip), quoteTraceValue(dso), quoteTraceValue(ip), quoteTraceValue(callchain)); err != nil {
			return err
		}
	}
	return nil
}

func rawPerfHeaderCPU(cpu int) int {
	if cpu < 0 {
		return 0
	}
	return cpu
}

func rawPerfIP(ip uint64) string {
	if ip == 0 {
		return "unknown"
	}
	return "0x" + strconv.FormatUint(ip, 16)
}

func rawPerfCallchain(sample rawPerfSample) string {
	parts := make([]string, 0, len(sample.Callchain)+1)
	for i := len(sample.Callchain) - 1; i >= 0; i-- {
		if sample.Callchain[i] != 0 {
			parts = append(parts, rawPerfIP(sample.Callchain[i]))
		}
	}
	if sample.IP != 0 {
		parts = append(parts, rawPerfIP(sample.IP))
	}
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(parts, ";")
}

func rawPerfDSO(mappings []rawPerfMapping, sample rawPerfSample) string {
	var best rawPerfMapping
	for _, mapping := range mappings {
		if mapping.Len == 0 || sample.IP < mapping.Addr || sample.IP >= mapping.Addr+mapping.Len {
			continue
		}
		if mapping.PID > 0 && sample.PID > 0 && mapping.PID != sample.PID {
			continue
		}
		if best.Len == 0 || mapping.Len < best.Len {
			best = mapping
		}
	}
	if best.Path == "" {
		return "unknown"
	}
	return best.Path
}
