package agent

import (
	"strings"
	"testing"

	"github.com/hanchaoqun/codrax/internal/skill"
	"github.com/hanchaoqun/codrax/internal/types"
)

// G4-1 (post_v2_runtime_gap_remediation, 2026-05-04). Extends the
// jargon audit from static skill corpora to the dynamic prose
// generated by answerDocumentEvaluator.BuildInitialInstruction (and
// every render* helper it transitively calls).
//
// Scope: the audit drives one AgentContext per family (root cause /
// config / enumeration / generic explanation) plus one with a
// retry-state attached, calls BuildInitialInstruction, concatenates
// the output, and greps every InternalTermsBlocklist token.
//
// Failure mode: any blocklist hit names the offending token + a
// short preview so the writer can locate the leak. The test is
// FATAL — a future writer who pastes a Go type name into a render*
// helper hits the test before code review.

func TestAnswerDocumentEvaluator_DynamicProse_NoInternalJargon(t *testing.T) {
	cases := []struct {
		name string
		ctx  *types.AgentContext
	}{
		{
			name: "root_cause_with_log",
			ctx: &types.AgentContext{
				AnalysisIR: &types.AnalysisIR{
					RequestModel: types.RequestModel{
						Intent:    types.IntentRootCause,
						LogTriage: &types.LogBundle{},
					},
				},
			},
		},
		{
			name: "config_query",
			ctx: &types.AgentContext{
				AnalysisIR: &types.AnalysisIR{
					RequestModel: types.RequestModel{Intent: types.IntentConfigQuery},
				},
			},
		},
		{
			name: "enumeration",
			ctx: &types.AgentContext{
				AnalysisIR: &types.AnalysisIR{
					RequestModel: types.RequestModel{Intent: types.IntentEnumerate},
				},
			},
		},
		{
			name: "explanation_with_subject",
			ctx: &types.AgentContext{
				AnalysisIR: &types.AnalysisIR{
					RequestModel: types.RequestModel{
						Intent: types.IntentExplain,
						AnswerSubject: types.AnswerSubject{
							Kind:       types.SubjectFunctionName,
							Confidence: 0.8,
						},
					},
				},
			},
		},
		{
			name: "trace_call_chain",
			ctx: &types.AgentContext{
				AnalysisIR: &types.AnalysisIR{
					RequestModel: types.RequestModel{Intent: types.IntentTrace},
				},
			},
		},
		{
			name: "retry_attempt",
			ctx: &types.AgentContext{
				AnalysisIR: &types.AnalysisIR{
					RequestModel: types.RequestModel{Intent: types.IntentTrace},
				},
				EmitStageRetryAttempt: 1,
				Mutable: func() *types.MutableState {
					mut := &types.MutableState{}
					mut.SetRetryState(&types.RetryState{
						Attempt: 1,
						ActiveViolations: []types.ScoredViolation{
							{Kind: types.ViolFacetUncovered, Severity: types.SeverityHigh,
								Detail: "facet_x uncovered", Layer: "v2_oracle"},
						},
					})
					return mut
				}(),
			},
		},
	}

	ev := &answerDocumentEvaluator{}
	emptySkill := &skill.Config{Name: "answer_document"}

	var corpus strings.Builder
	for _, c := range cases {
		out := ev.BuildInitialInstruction(c.ctx, emptySkill)
		corpus.WriteString("\n\n=== fixture: " + c.name + " ===\n")
		corpus.WriteString(out)
	}

	body := corpus.String()
	hits := scanLLMFacingForBlocklist(t, body)
	if len(hits) == 0 {
		return
	}
	for _, h := range hits {
		t.Errorf("  %s", h)
	}
	t.Fatalf("found %d jargon violation(s) in dynamic prose; rephrase in user-facing language or extend internal/skill/glossary.go :: InternalTermsBlocklist", len(hits))
}

// scanLLMFacingForBlocklist mirrors the matcher in
// internal/skill/glossary_test.go — short uppercase acronyms use
// whole-word matching; everything else is plain Contains.
func scanLLMFacingForBlocklist(t *testing.T, body string) []string {
	t.Helper()
	var hits []string
	for _, term := range skill.InternalTermsBlocklist {
		if term == "" {
			continue
		}
		idx := findLeakedTerm(body, term)
		if idx < 0 {
			continue
		}
		hits = append(hits, "token="+term+" preview="+previewSurrounding(body, idx, len(term)))
	}
	return hits
}

func findLeakedTerm(body, term string) int {
	if isShortUpperAcronymToken(term) {
		return findWholeWordToken(body, term)
	}
	return strings.Index(body, term)
}

func isShortUpperAcronymToken(s string) bool {
	if len(s) > 4 {
		return false
	}
	for _, r := range s {
		if r < 'A' || r > 'Z' {
			return false
		}
	}
	return len(s) >= 2
}

func findWholeWordToken(body, term string) int {
	from := 0
	for {
		i := strings.Index(body[from:], term)
		if i < 0 {
			return -1
		}
		pos := from + i
		left := pos == 0 || !isWordCharByte(body[pos-1])
		end := pos + len(term)
		right := end == len(body) || !isWordCharByte(body[end])
		if left && right {
			return pos
		}
		from = pos + 1
		if from >= len(body) {
			return -1
		}
	}
}

func isWordCharByte(b byte) bool {
	return (b >= 'A' && b <= 'Z') || (b >= 'a' && b <= 'z') || (b >= '0' && b <= '9') || b == '_'
}

func previewSurrounding(s string, start, length int) string {
	const window = 50
	from := start - window
	if from < 0 {
		from = 0
	}
	to := start + length + window
	if to > len(s) {
		to = len(s)
	}
	snippet := s[from:to]
	snippet = strings.ReplaceAll(snippet, "\n", " / ")
	snippet = strings.ReplaceAll(snippet, "\t", " ")
	return "…" + snippet + "…"
}
