package render

import (
	"strings"
	"testing"

	"github.com/hanchaoqun/codrax/internal/types"
)

// answerdoc_display_attachment_panel_test.go — P2-1 pins (§29.47.1
// follow-up, 2026-07-12): the display-attachment panel lead-in forks on the
// typed Source class. SYSTEM-authored deterministic content (the cross-check
// appendix, review notes) opens under the system's own voice; only preserved
// MODEL output keeps the model-provenance lead-in. Witness: the donghu
// 100418 replay introduced the 系统校验附注 as 「来自模型已生成…按原文保留」.

// TestDisplayAttachmentPanelSourceFork — one model attachment + one system
// attachment: two panels, each under its own lead-in, appendix never under
// the model-provenance wording.
func TestDisplayAttachmentPanelSourceFork(t *testing.T) {
	out := RenderAnswerDocumentWithAttachments(truncTestDoc(), []types.AnswerDisplayAttachment{
		{
			Kind:   types.AnswerDisplayAttachmentMarkdown,
			Title:  "第一稿答案（校验前参考）",
			Body:   "第一稿正文内容。",
			Source: "orchestrator.first_finalize_draft",
		},
		{
			Kind:   types.AnswerDisplayAttachmentMarkdown,
			Title:  "系统校验附注",
			Body:   "以下为系统机械交叉核对结果，供参考，可能存在误报；以正文与证据为准。\n\n- 示例核对项",
			Source: types.AnswerDisplayAttachmentSourceSystemCrossCheck,
		},
	}, "zh")
	if !strings.Contains(out, "系统保留内容") || !strings.Contains(out, "来自模型已生成") {
		t.Fatalf("the model-provenance panel must keep its incumbent lead-in:\n%.600s", out)
	}
	if !strings.Contains(out, "系统生成内容") || !strings.Contains(out, "以下为系统生成的确定性内容") {
		t.Fatalf("the system-authored panel must open in the system's own voice:\n%s", out)
	}
	modelPanel := strings.Index(out, "系统保留内容")
	systemPanel := strings.Index(out, "系统生成内容")
	appendix := strings.Index(out, "系统校验附注")
	if !(modelPanel < systemPanel && systemPanel < appendix) {
		t.Fatalf("the appendix must render inside the system panel (model panel first): model=%d system=%d appendix=%d", modelPanel, systemPanel, appendix)
	}
	// DISPLAY-HYG 二轮 catalog C6: the first panel's closing rule and the
	// second panel's opening rule collapse into ONE separator — no
	// consecutive `---` lines anywhere in the render.
	if strings.Contains(out, "---\n\n---") {
		t.Fatalf("catalog C6: consecutive horizontal rules must collapse:\n%s", out)
	}
}

// TestDisplayAttachmentPanelSystemOnly — a system-only attachment set must
// never render the model-provenance lead-in at all.
func TestDisplayAttachmentPanelSystemOnly(t *testing.T) {
	for _, lang := range []string{"zh", "en"} {
		out := RenderAnswerDocumentWithAttachments(truncTestDoc(), []types.AnswerDisplayAttachment{{
			Kind:   types.AnswerDisplayAttachmentMarkdown,
			Title:  "系统校验附注",
			Body:   "示例核对内容。",
			Source: types.AnswerDisplayAttachmentSourceSystemCrossCheck,
		}}, lang)
		if strings.Contains(out, "来自模型已生成") || strings.Contains(out, "generated by the model but could not be fully preserved") {
			t.Fatalf("[%s] system-only content must never open under the model-provenance lead-in:\n%s", lang, out)
		}
		if !strings.Contains(out, "系统生成内容") && !strings.Contains(out, "System-generated content") {
			t.Fatalf("[%s] the system-voice lead-in must be present:\n%s", lang, out)
		}
	}
}
